name: devops_noods

on: 
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install sshpass
        run: sudo apt-get install sshpass  

      - name: Connect to server via SSH using password
        env: 
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          USER_HOST: ${{ secrets.USER_HOST }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$USER_HOST"@139.180.158.237 "exit" \
          && echo "Connection successful!" \
          || (echo "Connection failed!" && exit 1)
      
      - name: Sync latest code to repository
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          USER_HOST: ${{ secrets.USER_HOST }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$USER_HOST"@139.180.158.237 << 'EOF'
            echo "SSH connection successful!"
            
            git clone https://github.com/Tran02Thi/CyberSkill.git cyberskill && cd cyberskill
            
            git reset --hard
            git pull origin main
            echo "Code updated successfully!"
          EOF
          
