name: devops_noods

on: 
  push:
    branches:
      - feature/devops

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # - name: checkout code
      #   uses: actions/checkout@v2
      #   with:
      #     ref: feature/devops

      - name: show api key
        run: |
          echo "API Key: ${{API}}"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout deploy
        run: |
          echo "Deploy thành công"