name: devops_noods

on:
  push:
    branches:
      - feature/devops

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          ref: feature/devops

      - name: list files
      run: |
        echo "Liệt kê các file"
        ls -R 