name: devops_noods

on: 
  push:
    branches:
      - main

jobs:
  build_and_sync_code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install sshpass
        run: sudo apt-get install sshpass  

      - name: Connect to server via SSH using password
        env: 
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          USER_HOST: ${{ secrets.USER_HOST }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$USER_HOST"@139.180.158.237 "exit" \
          && echo "Connection successful!" \
          || (echo "Connection failed!" && exit 1)
      
      - name: Sync latest code to repository
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          USER_HOST: ${{ secrets.USER_HOST }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$USER_HOST"@139.180.158.237 << 'EOF'
            
            if ! command -v git &> /dev/null
            then
              echo "Git not found, installing..."
              sudo apt-get update && sudo apt-get install -y git
            fi

            if [ ! -d "cyberskill" ]; then
              echo "Creating directory cyberskill"
              mkdir -p cyberskill
            fi
            echo "Setting permissions for cyberskill"
            chmod -R 755 cyberskill
            chown -R $USER:$USER cyberskill

            # Check if the repo is already cloned, if not clone it
            if [ ! -d "cyberskill/.git" ]; then
              echo "Repository not found, cloning..."
              git clone https://github.com/Tran02Thi/CyberSkill.git cyberskill
            else
              echo "Repository found, pulling latest changes..."
              cd cyberskill
              git reset --hard
              git pull origin main
            fi
            
            echo "Code updated successfully!"
          
          EOF

  deploy:
      runs-on: ubuntu-latest
      needs: build_and_sync_code
      steps:
        - name: Check out the repository
          uses: actions/checkout@v3
          with:
            ref: main
          
        - name: Install sshpass
          run: sudo apt-get install sshpass 
        
        - name: Run deployment script on server
          env:
            SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
            USER_HOST: ${{ secrets.USER_HOST }}
          run: |
            sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$USER_HOST"@139.180.158.237 << 'EOF'
              echo "Starting deployment..."

              cd cyberskill

              chmod +x scripts.sh
              ./scripts.sh

              echo "Deployment completed successfully!"
            EOF