name: devops_noods

on: 
  push:
    branches:
      - feature/devops
    paths:
      - 'seasson2/**'
      - 'index.html'

jobs:
  build_and_test:
   runs-on: ubuntu-latest

    steps:
     - name: Check out the repository
       uses: actions/checkout@v3
       with:
         ref: feature/devops

     - name: Set up dependencies
       run: |
         sudo apt-get update
         sudo apt-get install -y poppler-utils

     - name: Run script.sh
       run: |
         chmod +x scripts.sh
         bash scripts.sh seasson2

     - name: Commit and push changes to feature/devops branch
       run: |
         git config --global user.name "ThiTV"
         git config --global user.email "ThiTV@vetc.com.vn"
         git add .
         git commit -m "upload file pdf" || echo "No changes to commit"
         git push origin feature/devops
       env:
         GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Deploy to EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./index.html"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo service nginx restart