name: devops_noods

on: 
  push:
    branches:
      - feature/devops

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
            JAVA_VERSION: '21'
    steps:
      # - name: checkout code
      #   uses: actions/checkout@v2
      #   with:
      #     ref: feature/devops

      - name: show api key and version JAVA
        run: |
          echo "API Key: ${{secrets.API}} and Version: ${{env.JAVA_VERSION}}"
          echo "Docker user: ${{vars.DOCKER_USER}}"
  scripts:
    runs-on: ubuntu-latest
    
    steps:
      - name: run scripts
        run: |
          chmod +x .github/scripts/custom.sh 
          .github/scripts/custom.sh
        shell: bash


  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout deploy
        run: |
          echo "Deploy thành công"