name: devops_noods

on: 
  push:
    branches:
      - feature/devops
    paths:
      - 'seasson2/**'


jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          ref: feature/devops

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils 

      - name: Run script.sh
        run: |
          chmod +x scripts.sh
          scripts.sh "seasson2" 

  # scripts:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - name: run scripts
  #       run: |
  #         chmod +x .github/scripts/custom.sh
  #       shell:  bash


  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout deploy
        run: |
          echo "Deploy thành công"

# name: devops_noods

# on: 
#   push:
#     branches:
#       - feature/devops

# jobs:
#   build_and_test:
#     runs-on: ubuntu-latest
#     env:
#       JAVA_VERSION: '21'
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Show API key and Java version
#         run: |
#           echo "API Key: ${{ secrets.API }} and Version: ${{ env.JAVA_VERSION }}"
#           echo "Docker user: ${{ vars.DOCKER_USER }}"

#   scripts:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Run custom script
#         run: |
#           chmod +x .github/scripts/custom.sh
#           ./.github/scripts/custom.sh
#         shell: bash

#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy step
#         run: |
#           echo "Deploy thành công"
